name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.ftp.pyramidempilhadeiras.com.br }} 
        user: ${{ secrets.pyramidempilhade1 }}
        password: ${{ secrets.PASS }}
        localDir: "PYRAMID-EMPILHADEIRA"               
               
               
               
  
            